sudo: required
dist: trusty
language: python

virtualenv:
  system_site_packages: true

python:
  - 3.4

env:
  global:
    - QT_BASE=57

before_install:
  - sudo add-apt-repository ppa:ubuntu-sdk-team/ppa --yes
  - sudo add-apt-repository ppa:terry.guo/gcc-arm-embedded --yes
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test --yes
  - sudo add-apt-repository ppa:beineri/opt-qt571-trusty --yes
  - sudo apt-get update -qq

install:
  - sudo apt-get --yes --force-yes install python3-pyqt5 curl gcc-arm-none-eabi libmpfr4 libmpc3 libfox-1.6-dev libgtest-dev
  - wget --quiet https://launchpad.net/ubuntu/+source/gcc-avr/1:4.9.2+Atmel3.5.0-1/+build/8403710/+files/gcc-avr_4.9.2+Atmel3.5.0-1_amd64.deb
  - wget --quiet https://launchpad.net/ubuntu/+source/avr-libc/1:1.8.0+Atmel3.5.0-1/+build/8435473/+files/avr-libc_1.8.0+Atmel3.5.0-1_all.deb
  - wget --quiet https://launchpad.net/ubuntu/+source/binutils-avr/2.25+Atmel3.5.0-2/+build/8435474/+files/binutils-avr_2.25+Atmel3.5.0-2_amd64.deb
  - sudo dpkg --install gcc-avr_4.9.2+Atmel3.5.0-1_amd64.deb avr-libc_1.8.0+Atmel3.5.0-1_all.deb binutils-avr_2.25+Atmel3.5.0-2_amd64.deb
  - sudo apt-get install -qq qt${QT_BASE}base qt${QT_BASE}multimedia qt${QT_BASE}tools; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh

script:
  - ./tools/commit-tests.sh
