sudo: required
dist: xenial
language: cpp
compiler: gcc

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-sdk-team/ppa'
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
      - sourceline: 'ppa:beineri/opt-qt571-xenial'
    update: true
    packages:
      - curl
      - libmpfr4
      - libmpc3
      - libfox-1.6-dev
      - libgtest-dev
      - lib32stdc++6
      - libclang-common-6.0-dev
      - clang-6.0
      - python3-pip

env:
  global:
    - QT_BASE=57
    - GCC_ARM_VERSION=4_7-2013q3
  matrix:
    - FLAVOR=COMPANION
    - FLAVOR=ARM9X
    - FLAVOR=X9LITE
    - FLAVOR=X7
    - FLAVOR=XLITE
    - FLAVOR=X9
    - FLAVOR=COLORLCD

before_install:
  - wget --quiet https://launchpad.net/gcc-arm-embedded/4.7/4.7-2013-q3-update/+download/gcc-arm-none-eabi-${GCC_ARM_VERSION}-20130916-linux.tar.bz2
  - tar xjf gcc-arm-none-eabi-${GCC_ARM_VERSION}-20130916-linux.tar.bz2
  - sudo mv gcc-arm-none-eabi-${GCC_ARM_VERSION} /opt/gcc-arm-none-eabi
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-gcc /usr/bin/arm-none-eabi-gcc
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-g++ /usr/bin/arm-none-eabi-g++
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-as /usr/bin/arm-none-eabi-as
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-objcopy /usr/bin/arm-none-eabi-objcopy
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-objdump /usr/bin/arm-none-eabi-objdump
  - sudo ln -s /opt/gcc-arm-none-eabi/bin/arm-none-eabi-size /usr/bin/arm-none-eabi-size
  - sudo apt-get install --yes --force-yes -qq qt${QT_BASE}base qt${QT_BASE}multimedia qt${QT_BASE}svg qt${QT_BASE}tools; source /opt/qt${QT_BASE}/bin/qt${QT_BASE}-env.sh
  - sudo ln -sf /usr/bin/python3 /usr/bin/python
  - python3 -m pip install pip==20.3.3
  - sudo apt-get install python3-setuptools
  - python3 -m pip install pillow clang

script:
  - ./tools/commit-tests.sh
