name: Do Linux nightly Companion

on:
  workflow_run:
    workflows: ["Do MacOSX nightly Companion"]
    types:
      - completed
     
  workflow_dispatch:  
     
env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-18.04

    steps:      
    - name: Init
      run: sudo apt update
      
    - name: Install dependencies
      run: sudo apt-get -y install build-essential cmake gcc git lib32ncurses5 lib32z1 libfox-1.6-dev libsdl1.2-dev
          qt5-default qtmultimedia5-dev qttools5-dev qttools5-dev-tools libqt5svg5-dev
          software-properties-common wget zip libgtest-dev libclang1-7 python3-pip
          
    - name: Install cross compiler
      run: wget -q https://launchpad.net/gcc-arm-embedded/4.7/4.7-2013-q3-update/+download/gcc-arm-none-eabi-4_7-2013q3-20130916-linux.tar.bz2 &&
          tar xjf gcc-arm-none-eabi-4_7-2013q3-20130916-linux.tar.bz2 &&
          mv gcc-arm-none-eabi-4_7-2013q3 /opt/gcc-arm-none-eabi &&
          echo "/opt/gcc-arm-none-eabi/bin:/opentx/code/radio/util" >> $GITHUB_PATH

    - name: Install pillow      
      run: python -m pip install filelock clang pillow

    - uses: actions/checkout@v2
    - name: Create Build Environment
      # Some projects don't allow in-source building, so create a separate build directory
      # We'll use this as our working directory for all subsequent commands
      run: cmake -E make_directory ${{github.workspace}}/build
      
    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      # Execute the build.  You can specify a specific target with "--target <NAME>"
      run: mkdir ${{github.workspace}}/output && tools/build-companion-nightly.sh ${{github.workspace}}  ${{github.workspace}}/output/
      
    - uses: eine/tip@master
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: 'nightly'
        files: ${{github.workspace}}/output/*.deb
   
